name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.MY_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GITLAB_COM_TOKEN: ${{ secrets.GITLAB_COM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Clean
        run: ./gradlew --no-daemon clean

      - name: CodeNarc
        run: ./gradlew --no-daemon codenarcMain codenarcTest codenarcIntegrationTest

      - name: Test
        run: ./gradlew --no-daemon test

      - name: IntegrationTest
        run: ./gradlew --no-daemon integrationTest --info

      - name: Build
        run: ./gradlew --no-daemon build -x codenarcMain -x codenarcTest -x codenarcIntegrationTest
