info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
environments:
  development:
    server:
      port : 8090
dataSource:
  url: jdbc:mysql://localhost:3316/uberall?useSSL=false&allowPublicKeyRetrieval=true
  driverClassName: com.mysql.cj.jdbc.Driver
  dbCreate: none
  username: uberall
  password: '123456'
  pooled: true
  jmxExport: true
  properties:
    maxActive: -1
    minEvictableIdleTimeMillis: 1800000
    timeBetweenEvictionRunsMillis: 1800000
    numTestsPerEvictionRun: 3
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    validationQuery: "SELECT 1"
  dialect: org.hibernate.dialect.MySQL8Dialect
grails:
  gorm:
    default:
      mapping:
        user-types:
          - type: org.jadira.usertype.dateandtime.joda.CustomPersistentDateTime
            class: org.joda.time.DateTime
          - type: org.jadira.usertype.dateandtime.joda.PersistentLocalDate
            class: org.joda.time.LocalDate
        '*':
          cascadeValidate: 'default'
    reactor:
      events: false
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
hibernate:
  hbm2ddl:
    auto: none
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

spring:
  liquibase:
    # Auto-run disabled per request. Enable manually if needed.
    enabled: false
    change-log: classpath:grails-app/migrations/changelog.groovy

---
grails:
  redis:
    port: 6389
    host: localhost

---
googlemaps:
  url: https://maps.googleapis.com/maps
  key: AIzaSyBk7Gxehjb1f5wcrECcPLApZMesrM-utNc

---
grails:
  plugin:
    databasemigration:
      updateOnStart: false
      changelogFileName: changelog.groovy
      updateOnStartFileNames:
        - changelog.groovy
